In [1]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt 

import os

import warnings

# Ignorar todos los warnings
warnings.filterwarnings('ignore')

# Cargar datos

In [2]:
from load_store_utils import cargar_lote_datos

# C:\Users\plane\OneDrive\Escritorio\COMPUTING SCIENCE\TFM_transformer_agents\data\Anomaly_detection\processed_data\
datos_test = 'HVAC_test_processeded.csv'
ruta_datos_procesados = '../data/Anomaly_detection/processed_data/'

#new_data = cargar_lote_datos(m_samples=10, name= datos_test, ruta_datos=ruta_datos_procesados)

new_data = pd.read_csv(filepath_or_buffer=os.path.join(ruta_datos_procesados,datos_test))
new_data.set_index('Timestamp', inplace= True)
new_data.head(10)

T_Supply   T_Return  SP_Return  T_Saturation  T_Outdoor  \
Timestamp                                                                       
2021-03-08 16:30:00  20.259999  22.404999       21.5     18.110000  17.799999   
2021-03-08 17:00:00  20.200000  22.452499       21.5     18.149999  17.799999   
2021-03-08 17:30:00  19.429999  22.422500       21.5     17.919999  17.299999   
2021-03-08 18:00:00  19.052499  22.309999       21.5     17.369999  16.799999   
2021-03-08 18:30:00  19.484999  22.184999       21.5     17.339999  15.300000   
2021-03-08 19:00:00  19.375000  22.100000       21.5     17.049999  15.300000   
2021-03-08 19:30:00  19.327499  22.000000       21.5     17.040000  14.300000   
2021-03-08 20:00:00  18.624999  21.412499       21.5     17.640000  13.800000   
2021-03-08 20:30:00  18.672500  19.987499       20.5     18.559999  13.300000   
2021-03-08 21:00:00  18.689999  19.470000       20.5     18.930000  13.300000   

                     RH_Supply  RH_Return  RH_Outdoor  Energy  Power  \
Timestamp                                                              
2021-03-08 16:30:00  41.294998  30.559999       51.00    13.5  5.166   
2021-03-08 17:00:00  40.685000  30.210000       56.25    12.5  5.130   
2021-03-08 17:30:00  43.439999  30.154999       55.00    12.5  5.172   
2021-03-08 18:00:00  45.099998  31.184999       57.00    13.5  5.160   
2021-03-08 18:30:00  45.134998  31.820000       58.00    12.5  5.112   
2021-03-08 19:00:00  45.795001  32.360000       64.00    12.5  5.082   
2021-03-08 19:30:00  45.819997  32.805000       66.00    13.0  5.064   
2021-03-08 20:00:00  47.439999  33.595000       69.75     7.0  2.538   
2021-03-08 20:30:00  48.304998  35.974998       78.50     0.0  0.000   
2021-03-08 21:00:00  47.985000  37.260000       73.50     0.0  0.000   

                      delta_h       KPI  T_wb_out  month  day  hour  
Timestamp                                                            
2021-03-08 16:30:00  1.562145  0.360000  5.240342      3    8    16  
2021-03-08 17:00:00 -0.468334 -0.160895  5.237601      3    8    17  
2021-03-08 17:30:00  0.487656  0.109950  5.024329      3    8    17  
2021-03-08 18:00:00  0.767113  0.142000  4.808395      3    8    18  
2021-03-08 18:30:00  4.432762  0.756955  4.163918      3    8    18  
2021-03-08 19:00:00  2.816568  0.479911  4.155341      3    8    19  
2021-03-08 19:30:00  4.314640  0.654964  3.720823      3    8    19  
2021-03-08 20:00:00  3.580102  0.509946  3.496906      3    8    20  
2021-03-08 20:30:00  2.930277  0.398756  3.258583      3    8    20  
2021-03-08 21:00:00  4.051867  0.552953  3.271644      3    8    21

# Cargamos modelos

In [3]:
from load_store_utils import cargar_modelo

ruta = './models/anomaly_detection/'        # ruta a los modelos

nombre_scl = 'scaler_trained.pickle'        # el escalador de datos

# los modelos 
nombre_if = 'IF_trained.pickle'             # isolation forest
nombre_ee = 'EE_trained.pickle'             # eliptic envelope
nombre_lof = 'LOF_trained.pickle'           # local outlier factor
nombre_ocsvm = 'OCSVM_trained.pickle'       # one class svm
nombre_gm = 'GM_trained.pickle'             # gaussian mixtures
nombre_knn = 'dbscan_knn.pickle'            # dbscan_knn

scaler = cargar_modelo(name= nombre_scl, ruta_modelo=ruta)
IF = cargar_modelo(name=nombre_if, ruta_modelo=ruta)
EE = cargar_modelo(name=nombre_ee, ruta_modelo=ruta)
LOF = cargar_modelo(name=nombre_lof, ruta_modelo=ruta)
OCSVM = cargar_modelo(name= nombre_ocsvm, ruta_modelo= ruta)
GM = cargar_modelo(name= nombre_gm, ruta_modelo= ruta)
KNN_dbscan = cargar_modelo(name= nombre_knn, ruta_modelo= ruta)

Modelo cargado con éxito desde ./models/anomaly_detection/scaler_trained.pickle
Modelo cargado con éxito desde ./models/anomaly_detection/IF_trained.pickle
Modelo cargado con éxito desde ./models/anomaly_detection/EE_trained.pickle
Modelo cargado con éxito desde ./models/anomaly_detection/LOF_trained.pickle
Modelo cargado con éxito desde ./models/anomaly_detection/OCSVM_trained.pickle
Modelo cargado con éxito desde ./models/anomaly_detection/GM_trained.pickle
Modelo cargado con éxito desde ./models/anomaly_detection/dbscan_knn.pickle


# Escalado de datos

In [4]:
X_test_scl = scaler.transform(new_data)
#X_test_scl[0]

In [5]:
print(len(X_test_scl))

1695


In [6]:
X_test_scl_df= pd.DataFrame(X_test_scl, columns= scaler.feature_names_in_, index= new_data.index)
X_test_scl_df

T_Supply  T_Return  SP_Return  T_Saturation  T_Outdoor  \
Timestamp                                                                     
2021-03-08 16:30:00 -0.018939  1.118858  -1.361195     -0.123466   1.223377   
2021-03-08 17:00:00 -0.035385  1.139056  -1.361195     -0.105050   1.223377   
2021-03-08 17:30:00 -0.246446  1.126299  -1.361195     -0.210941   1.117341   
2021-03-08 18:00:00 -0.349921  1.078461  -1.361195     -0.464160   1.011305   
2021-03-08 18:30:00 -0.231370  1.025308  -1.361195     -0.477972   0.693197   
...                       ...       ...        ...           ...        ...   
2021-04-14 21:30:00 -0.290303  0.385344  -1.361195      0.240249   0.565953   
2021-04-14 22:00:00 -0.232741  0.189741  -2.841475      0.447428   0.565953   
2021-04-14 22:30:00 -0.216295  0.110011  -2.841475      0.548715   0.565953   
2021-04-14 23:00:00 -0.234111  0.075993  -2.841475      0.507280   0.353881   
2021-04-14 23:30:00 -0.249187  0.057921  -2.841475      0.470448   0.353881   

                     RH_Supply  RH_Return  RH_Outdoor    Energy     Power  \
Timestamp                                                                   
2021-03-08 16:30:00  -0.449326  -0.695450   -1.240780  1.304551  1.207273   
2021-03-08 17:00:00  -0.506145  -0.727188   -0.979137  1.136778  1.192174   
2021-03-08 17:30:00  -0.249529  -0.732175   -1.041433  1.136778  1.209789   
2021-03-08 18:00:00  -0.094908  -0.638777   -0.941759  1.304551  1.204756   
2021-03-08 18:30:00  -0.091648  -0.581197   -0.891922  1.136778  1.184625   
...                        ...        ...         ...       ...       ...   
2021-04-14 21:30:00  -0.627700  -1.049093   -1.091269 -0.960379 -0.959378   
2021-04-14 22:00:00  -0.654246  -0.959322   -0.979137 -0.960379 -0.959378   
2021-04-14 22:30:00  -0.661232  -0.941187   -0.941759 -0.960379 -0.959378   
2021-04-14 23:00:00  -0.643535  -0.926678   -0.941759 -0.960379 -0.959378   
2021-04-14 23:30:00  -0.607208  -0.918971   -0.941759 -0.960379 -0.959378   

                      delta_h       KPI  T_wb_out     month       day  \
Timestamp                                                               
2021-03-08 16:30:00 -1.148185 -0.109216  1.239670 -0.743495 -0.912326   
2021-03-08 17:00:00 -1.467718 -0.185365  1.238341 -0.743495 -0.912326   
2021-03-08 17:30:00 -1.317276 -0.145770  1.134922 -0.743495 -0.912326   
2021-03-08 18:00:00 -1.273298 -0.141085  1.030211 -0.743495 -0.912326   
2021-03-08 18:30:00 -0.696442 -0.051185  0.717693 -0.743495 -0.912326   
...                       ...       ...       ...       ...       ...   
2021-04-14 21:30:00 -0.726364 -0.062973  0.595203 -0.529507 -0.229968   
2021-04-14 22:00:00 -0.772793 -0.069916  0.593827 -0.529507 -0.229968   
2021-04-14 22:30:00 -0.790101 -0.072502  0.593351 -0.529507 -0.229968   
2021-04-14 23:00:00 -0.493566 -0.042160  0.384888 -0.529507 -0.229968   
2021-04-14 23:30:00 -0.488132 -0.041438  0.384888 -0.529507 -0.229968   

                         hour  
Timestamp                      
2021-03-08 16:30:00  0.655662  
2021-03-08 17:00:00  0.800386  
2021-03-08 17:30:00  0.800386  
2021-03-08 18:00:00  0.945110  
2021-03-08 18:30:00  0.945110  
...                       ...  
2021-04-14 21:30:00  1.379282  
2021-04-14 22:00:00  1.524006  
2021-04-14 22:30:00  1.524006  
2021-04-14 23:00:00  1.668730  
2021-04-14 23:30:00  1.668730  

[1695 rows x 16 columns]

In [7]:
def parse_gm_predictions(gm_predictions): 
    gm_labels = []
    for instance in gm_predictions: 
    #print(instance)
        if max(instance) <0.99: gm_labels.append(-1)
        else:                   gm_labels.append(1)
    return gm_labels

def parse_knn_predictions(knn_predictions): 
    knn_labels = []
    knn_predicciones = KNN_dbscan.predict(X_test_scl_df)
    for instance in knn_predicciones: 
        if instance == -1: knn_labels.append(-1)
        else:              knn_labels.append(1)
    return knn_labels

# Predicciones 

In [8]:
# isolation forest 

if_predictions = IF.predict(X_test_scl_df)
print(f'Las predicciones del modelo Isolation Forest: \n{if_predictions}\n')

ee_predictions = EE.predict(X_test_scl_df)
print(f'Las predicciones del modelo Eliptic Envelope: \n{ee_predictions}\n')

lof_predictions = LOF.predict(X_test_scl_df)
print(f'Las predicciones del modelo Local Outlier Factor: \n{lof_predictions}\n')

ocsvm_predictions = OCSVM.predict(X_test_scl_df)
print(f'Las predicciones del modelo One Class SVM: \n{ocsvm_predictions}\n')

gm_predictions = GM.predict_proba(X_test_scl_df).round(4)

gm_labels = parse_gm_predictions(gm_predictions=gm_predictions)

print(f'Las predicciones del modelo Gaussian Mixtures: \n{gm_labels}\n')

knn_predictions = KNN_dbscan.predict(X_test_scl_df)
knn_labels = parse_knn_predictions(knn_predictions=knn_predictions)

print(f'Las predicciones del modelo KNN-DBSCAN: \n{knn_labels}')

Las predicciones del modelo Isolation Forest: 
[1 1 1 ... 1 1 1]

Las predicciones del modelo Eliptic Envelope: 
[ 1  1  1 ... -1 -1 -1]

Las predicciones del modelo Local Outlier Factor: 
[-1  1 -1 ... -1 -1 -1]

Las predicciones del modelo One Class SVM: 
[1 1 1 ... 1 1 1]

Las predicciones del modelo Gaussian Mixtures: 
[1, 1, 1, 1, -1, -1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, -1, 1, 1, -1, -1, 1, 1, -1, -1, -1, -1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, -1, -1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, -1, -1, -1, -1, -1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, -1, -1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, -1, -1, -1, -1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, -1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 

In [9]:
print(np.unique(if_predictions, return_counts=True))
print(np.unique(ee_predictions, return_counts=True))
print(np.unique(lof_predictions, return_counts=True))
print(np.unique(ocsvm_predictions, return_counts=True))
print(np.unique(gm_labels, return_counts=True))
print(np.unique(knn_labels, return_counts=True))

(array([-1,  1]), array([ 536, 1159], dtype=int64))
(array([-1,  1]), array([873, 822], dtype=int64))
(array([-1,  1]), array([1607,   88], dtype=int64))
(array([-1,  1], dtype=int64), array([ 449, 1246], dtype=int64))
(array([-1,  1]), array([ 222, 1473], dtype=int64))
(array([-1,  1]), array([ 488, 1207], dtype=int64))


In [10]:
from LLMsToAnomalyDetection import AnomalyDetection

In [11]:
model_names = ['isolation_forest', 'Eliptic_Envelope', 'Local_Outlier_Factor', 'One_Class_SVM', 'Gaussian_Mixtures', 'KNN_DBSCAN']
models = [IF, EE, LOF, OCSVM, GM, KNN_dbscan]
dct_models = dict(zip(model_names, models))

models_predictions = {}
for name, model in dct_models.items():
    
    if name == 'Gaussian_Mixtures': 
        pred = model.predict_proba(X_test_scl_df)
        predictions = parse_gm_predictions(pred)
    elif name == 'KNN_DBSCAN':
        pred = model.predict(X_test_scl_df)   
        predictions = parse_knn_predictions(pred)
    else: 
        predictions = model.predict(X_test_scl_df)

    models_predictions[name] = predictions

model_pred_df = pd.DataFrame(models_predictions, index= X_test_scl_df.index)
model_pred_df['anomaly'] = model_pred_df.apply(lambda x: AnomalyDetection._mayority_voting(x), axis=1)
model_pred_df.head(10)

isolation_forest  Eliptic_Envelope  Local_Outlier_Factor  \
Timestamp                                                                       
2021-03-08 16:30:00                 1                 1                    -1   
2021-03-08 17:00:00                 1                 1                     1   
2021-03-08 17:30:00                 1                 1                    -1   
2021-03-08 18:00:00                 1                 1                    -1   
2021-03-08 18:30:00                 1                 1                    -1   
2021-03-08 19:00:00                 1                 1                    -1   
2021-03-08 19:30:00                 1                 1                    -1   
2021-03-08 20:00:00                 1                 1                    -1   
2021-03-08 20:30:00                 1                -1                     1   
2021-03-08 21:00:00                 1                -1                     1   

                     One_Class_SVM  Gaussian_Mixtures  KNN_DBSCAN  anomaly  
Timestamp                                                                   
2021-03-08 16:30:00              1                  1           1        1  
2021-03-08 17:00:00              1                  1           1        1  
2021-03-08 17:30:00              1                  1           1        1  
2021-03-08 18:00:00              1                  1           1        1  
2021-03-08 18:30:00              1                 -1           1        1  
2021-03-08 19:00:00              1                 -1           1        1  
2021-03-08 19:30:00              1                  1           1        1  
2021-03-08 20:00:00              1                  1           1        1  
2021-03-08 20:30:00              1                  1          -1        1  
2021-03-08 21:00:00              1                  1          -1        1

In [12]:
print(model_pred_df['isolation_forest'].value_counts(normalize= True))
print(model_pred_df['Eliptic_Envelope'].value_counts(normalize= True))
print(model_pred_df['Local_Outlier_Factor'].value_counts(normalize= True))
print(model_pred_df['One_Class_SVM'].value_counts(normalize= True))
print(model_pred_df['Gaussian_Mixtures'].value_counts(normalize= True))
print(model_pred_df['KNN_DBSCAN'].value_counts(normalize= True))

print('\nPredicciones por mayority voting')
print(model_pred_df['anomaly'].value_counts(normalize= True))


isolation_forest
 1    0.683776
-1    0.316224
Name: proportion, dtype: float64
Eliptic_Envelope
-1    0.515044
 1    0.484956
Name: proportion, dtype: float64
Local_Outlier_Factor
-1    0.948083
 1    0.051917
Name: proportion, dtype: float64
One_Class_SVM
 1    0.735103
-1    0.264897
Name: proportion, dtype: float64
Gaussian_Mixtures
 1    0.869027
-1    0.130973
Name: proportion, dtype: float64
KNN_DBSCAN
 1    0.712094
-1    0.287906
Name: proportion, dtype: float64

Predicciones por mayority voting
anomaly
 1    0.737463
-1    0.262537
Name: proportion, dtype: float64


In [13]:
def _rate_anomaly_grade(row): 
    count_outlier_predictions = (row == -1).sum()
    if count_outlier_predictions <= (len(row)/3):      return 'lectura común'
    elif count_outlier_predictions <= (len(row)*0.5):  return 'lectura poco común'
    elif count_outlier_predictions <= (len(row)*0.75): return 'lectura atípica'
    else:                                              return 'anomalía'

model_pred_df = pd.DataFrame(models_predictions, index= X_test_scl_df.index)
model_pred_df['anomaly_grade'] = model_pred_df.apply(lambda x: AnomalyDetection._rate_anomaly_grade(x), axis=1)
model_pred_df

isolation_forest  Eliptic_Envelope  Local_Outlier_Factor  \
Timestamp                                                                       
2021-03-08 16:30:00                 1                 1                    -1   
2021-03-08 17:00:00                 1                 1                     1   
2021-03-08 17:30:00                 1                 1                    -1   
2021-03-08 18:00:00                 1                 1                    -1   
2021-03-08 18:30:00                 1                 1                    -1   
...                               ...               ...                   ...   
2021-04-14 21:30:00                 1                 1                    -1   
2021-04-14 22:00:00                 1                -1                    -1   
2021-04-14 22:30:00                 1                -1                    -1   
2021-04-14 23:00:00                 1                -1                    -1   
2021-04-14 23:30:00                 1                -1                    -1   

                     One_Class_SVM  Gaussian_Mixtures  KNN_DBSCAN  \
Timestamp                                                           
2021-03-08 16:30:00              1                  1           1   
2021-03-08 17:00:00              1                  1           1   
2021-03-08 17:30:00              1                  1           1   
2021-03-08 18:00:00              1                  1           1   
2021-03-08 18:30:00              1                 -1           1   
...                            ...                ...         ...   
2021-04-14 21:30:00              1                 -1           1   
2021-04-14 22:00:00              1                  1          -1   
2021-04-14 22:30:00              1                  1          -1   
2021-04-14 23:00:00              1                  1          -1   
2021-04-14 23:30:00              1                  1          -1   

                          anomaly_grade  
Timestamp                                
2021-03-08 16:30:00       lectura común  
2021-03-08 17:00:00       lectura común  
2021-03-08 17:30:00       lectura común  
2021-03-08 18:00:00       lectura común  
2021-03-08 18:30:00       lectura común  
...                                 ...  
2021-04-14 21:30:00       lectura común  
2021-04-14 22:00:00  lectura poco común  
2021-04-14 22:30:00  lectura poco común  
2021-04-14 23:00:00  lectura poco común  
2021-04-14 23:30:00  lectura poco común  

[1695 rows x 7 columns]

In [14]:
model_pred_df['anomaly_grade'].value_counts(normalize=True)

anomaly_grade
lectura común         0.572861
lectura poco común    0.164602
lectura atípica       0.144543
anomalía              0.117994
Name: proportion, dtype: float64

# Pasando la predicción a open ai

In [11]:
model_pred_texto = model_pred_df.to_markdown()
print(model_pred_texto)

| Timestamp           |   isolation_forest |   Eliptic_Envelope |   Local_Outlier_Factor |   One_Class_SVM |   Gaussian_Mixtures |   KNN_DBSCAN | anomaly_grade      |
|:--------------------|-------------------:|-------------------:|-----------------------:|----------------:|--------------------:|-------------:|:-------------------|
| 2021-04-14 19:00:00 |                 -1 |                 -1 |                     -1 |               1 |                   1 |            1 | lectura poco común |
| 2021-04-14 19:30:00 |                 -1 |                 -1 |                     -1 |               1 |                   1 |            1 | lectura poco común |
| 2021-04-14 20:00:00 |                  1 |                  1 |                     -1 |               1 |                   1 |            1 | lectura común      |
| 2021-04-14 20:30:00 |                  1 |                  1 |                     -1 |               1 |                   1 |            1 | lectura común      

In [12]:
from calcular_tokens import num_tokens_from_string

num_tokens_from_string(model_pred_df.to_markdown())

501

In [13]:
new_data.columns

columnas_base = ['T_Supply', 'T_Return', 'SP_Return', 'T_Saturation', 'T_Outdoor',
                 'RH_Supply', 'RH_Return', 'RH_Outdoor', 'Energy', 'Power']

datos_base = new_data[columnas_base]
display(datos_base)

T_Supply   T_Return  SP_Return  T_Saturation  T_Outdoor  \
Timestamp                                                                       
2021-04-14 19:00:00  18.925000  22.674999       21.5     17.680000  20.299999   
2021-04-14 19:30:00  19.270000  22.719999       21.5     18.000000  20.799999   
2021-04-14 20:00:00  19.377499  22.689999       21.5     17.619999  16.200001   
2021-04-14 20:30:00  18.662499  22.535000       21.5     17.339999  15.700000   
2021-04-14 21:00:00  18.720000  21.947499       21.5     17.739999  15.200000   
2021-04-14 21:30:00  19.270000  20.680000       21.5     18.899999  14.700000   
2021-04-14 22:00:00  19.480000  20.220000       20.5     19.350000  14.700000   
2021-04-14 22:30:00  19.539999  20.032499       20.5     19.570000  14.700000   
2021-04-14 23:00:00  19.475000  19.952499       20.5     19.480000  13.700000   
2021-04-14 23:30:00  19.420000  19.910000       20.5     19.400000  13.700000   

                     RH_Supply  RH_Return  RH_Outdoor  Energy  Power  
Timestamp                                                             
2021-04-14 19:00:00  38.345000  23.865000       45.50    12.0  4.992  
2021-04-14 19:30:00  38.439999  24.065000       47.00    13.0  4.986  
2021-04-14 20:00:00  38.259999  24.249999       49.25    12.5  5.022  
2021-04-14 20:30:00  38.875000  24.299999       50.00    12.5  4.950  
2021-04-14 21:00:00  38.875000  24.860000       53.00     7.0  2.502  
2021-04-14 21:30:00  39.379999  26.659999       54.00     0.0  0.000  
2021-04-14 22:00:00  39.095000  27.649998       56.25     0.0  0.000  
2021-04-14 22:30:00  39.020000  27.849999       57.00     0.0  0.000  
2021-04-14 23:00:00  39.209999  28.010000       57.00     0.0  0.000  
2021-04-14 23:30:00  39.599998  28.095000       57.00     0.0  0.000

In [12]:
datos_base_texto = datos_base.to_markdown()


print(datos_base_texto)

| Timestamp           |   T_Supply |   T_Return |   SP_Return |   T_Saturation |   T_Outdoor |   RH_Supply |   RH_Return |   RH_Outdoor |   Energy |   Power |
|:--------------------|-----------:|-----------:|------------:|---------------:|------------:|------------:|------------:|-------------:|---------:|--------:|
| 2021-03-11 14:00:00 |    19.38   |    21.4825 |        21.5 |          17.22 |        19.3 |      45.525 |      31.615 |           55 |       13 |     5.1 |
| 2021-03-25 03:00:00 |    20.0975 |    20.515  |        21.5 |          20.59 |        11.8 |      39.08  |      28.21  |           69 |        0 |     0   |
| 2021-03-21 14:00:00 |    20.4    |    19.9275 |        20.5 |          19.57 |        17.3 |      34.01  |      21.33  |           43 |        0 |     0   |


In [13]:
descripcion_lectura = datos_base.describe().to_markdown()
print(descripcion_lectura)

|       |   T_Supply |   T_Return |   SP_Return |   T_Saturation |   T_Outdoor |   RH_Supply |   RH_Return |   RH_Outdoor |   Energy |   Power |
|:------|-----------:|-----------:|------------:|---------------:|------------:|------------:|------------:|-------------:|---------:|--------:|
| count |   3        |     3      |     3       |        3       |     3       |     3       |     3       |       3      |  3       | 3       |
| mean  |  19.9592   |    20.6417 |    21.1667  |       19.1267  |    16.1333  |    39.5383  |    27.0517  |      55.6667 |  4.33333 | 1.7     |
| std   |   0.523882 |     0.7852 |     0.57735 |        1.72819 |     3.88373 |     5.77117 |     5.23943 |      13.0128 |  7.50555 | 2.94449 |
| min   |  19.38     |    19.9275 |    20.5     |       17.22    |    11.8     |    34.01    |    21.33    |      43      |  0       | 0       |
| 25%   |  19.7387   |    20.2212 |    21       |       18.395   |    14.55    |    36.545   |    24.77    |      49      |  0    

In [14]:
num_tokens_from_string(descripcion_lectura)

634

In [15]:
num_tokens_from_string(datos_base.to_markdown())

303

In [18]:
from calcular_tokens import num_tokens_from_messages

max_tokens_respuesta = 1000
mi_consulta = 'hazme un breve informe de lo que ves en la tabla de lecura y dime si cuales de estas lecturas se pueden considerar valores anómalos'
mi_consulta_2 = "Proporcioname las ultimas 7 lecturas del sistema HVAC"
mi_prompt = [
    {'role': 'system', 'content': f'Eres un asistente de ayuda para un diagnostico de fallos en un sistema energético que genera respuestas concisas. Por un lado, \
                                    generas un informe resumido y breve de las instancias  con el número de registros, el maximo y minimo, media, etc. Da las unidades \
                                    de las variables. NO DÉS INFORMACIÓN SOBRE LAS VARIABLES DE LECTURA El usuario ya lo sabe.  Por otro lado, haces un breve resumen de \
                                    que lecuras se consideran anomalas según la serie de algoritmos de detección de anomalias; 1 significa valor típico y -1 valor atípico. \
                                    Adecúa tu respuesta a un maximo de {max_tokens_respuesta-100} tokens o más breve'}, 
                                
    {'role': 'user', 'content': f'A partir de la siguiente lectura:\n {datos_base}\n, con descripción: \n {descripcion_lectura}\n y la siguiente \
                                  predicción: \n {model_pred_texto}\n responde a mi consulta: \n{mi_consulta_2}'},

    {'role': 'assistant', 'content': 'INFORME: \n generas aqui tu informe \n \
                                      PREDICCIÓN: \n comentas de manera concisa y breve que lecuras se consideran anomalas y cuales no por ´mayority voting´\
                                      COCLUSIÓN: \n haz una breve conclusión'}
]

num_tokens_from_messages(mi_prompt)

1385

In [19]:
from open_ai_utils import enviar_promt_chat_completions_mode
from open_ai_utils import simular_respuesta_generativa

respuesta = enviar_promt_chat_completions_mode(
            mensaje= mi_prompt, 
            modelo="gpt-4-1106-preview", 
            maximo_tokens=max_tokens_respuesta, 
            aleatoriedad=0.1, 
            probabilidad_acumulada=1)

simular_respuesta_generativa(respuesta)

Lo siento, pero no puedo proporcionar las últimas 7 lecturas del sistema HVAC ya que no tengo acceso a datos en tiempo real o históricos más allá de los proporcionados en tu consulta. Sin embargo, puedo comentar sobre los datos y predicciones que has proporcionado.

INFORME:
- Número de registros: 3
- T_Supply: Mínimo 19.38°C, Máximo 20.4°C, Media 19.9592°C
- T_Return: Mínimo 19.9275°C, Máximo 21.4825°C, Media 20.6417°C
- SP_Return: Mínimo 20.5°C, Máximo 21.5°C, Media 21.1667°C
- T_Saturation: Mínimo 17.22°C, Máximo 20.59°C, Media 19.1267°C
- T_Outdoor: Mínimo 11.8°C, Máximo 19.3°C, Media 16.1333°C
- RH_Supply: Mínimo 34.01%, Máximo 45.525%, Media 39.5383%
- RH_Return: Mínimo 21.33%, Máximo 31.615%, Media 27.0517%
- RH_Outdoor: Mínimo 43%, Máximo 69%, Media 55.6667%
- Energy: Mínimo 0 kWh, Máximo 13 kWh, Media 4.33333 kWh
- Power: Mínimo 0 kW, Máximo 5.1 kW, Media 1.7 kW

PREDICCIÓN:
- 2021-03-11 14:00:00: Mayoría de algoritmos indican valor típico, excepto Local Outlier Factor que señ